/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as UsersRouteRouteImport } from './routes/users/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersIndexRouteImport } from './routes/users/index'
import { Route as CampaignsIndexRouteImport } from './routes/campaigns/index'
import { Route as CampaignsNewRouteImport } from './routes/campaigns/new'
import { Route as CampaignsCampaignIdRouteRouteImport } from './routes/campaigns/$campaignId/route'
import { Route as CampaignsCampaignIdIndexRouteImport } from './routes/campaigns/$campaignId/index'
import { Route as UsersUserIdCharactersRouteImport } from './routes/users/$userId.characters'
import { Route as CampaignsCampaignIdLoginRouteImport } from './routes/campaigns/$campaignId/login'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRouteRoute = UsersRouteRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UsersRouteRoute,
} as any)
const CampaignsIndexRoute = CampaignsIndexRouteImport.update({
  id: '/campaigns/',
  path: '/campaigns/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsNewRoute = CampaignsNewRouteImport.update({
  id: '/campaigns/new',
  path: '/campaigns/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsCampaignIdRouteRoute =
  CampaignsCampaignIdRouteRouteImport.update({
    id: '/campaigns/$campaignId',
    path: '/campaigns/$campaignId',
    getParentRoute: () => rootRouteImport,
  } as any)
const CampaignsCampaignIdIndexRoute =
  CampaignsCampaignIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => CampaignsCampaignIdRouteRoute,
  } as any)
const UsersUserIdCharactersRoute = UsersUserIdCharactersRouteImport.update({
  id: '/$userId/characters',
  path: '/$userId/characters',
  getParentRoute: () => UsersRouteRoute,
} as any)
const CampaignsCampaignIdLoginRoute =
  CampaignsCampaignIdLoginRouteImport.update({
    id: '/login',
    path: '/login',
    getParentRoute: () => CampaignsCampaignIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/users': typeof UsersRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/campaigns/$campaignId': typeof CampaignsCampaignIdRouteRouteWithChildren
  '/campaigns/new': typeof CampaignsNewRoute
  '/campaigns/': typeof CampaignsIndexRoute
  '/users/': typeof UsersIndexRoute
  '/campaigns/$campaignId/login': typeof CampaignsCampaignIdLoginRoute
  '/users/$userId/characters': typeof UsersUserIdCharactersRoute
  '/campaigns/$campaignId/': typeof CampaignsCampaignIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/campaigns/new': typeof CampaignsNewRoute
  '/campaigns': typeof CampaignsIndexRoute
  '/users': typeof UsersIndexRoute
  '/campaigns/$campaignId/login': typeof CampaignsCampaignIdLoginRoute
  '/users/$userId/characters': typeof UsersUserIdCharactersRoute
  '/campaigns/$campaignId': typeof CampaignsCampaignIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/users': typeof UsersRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/campaigns/$campaignId': typeof CampaignsCampaignIdRouteRouteWithChildren
  '/campaigns/new': typeof CampaignsNewRoute
  '/campaigns/': typeof CampaignsIndexRoute
  '/users/': typeof UsersIndexRoute
  '/campaigns/$campaignId/login': typeof CampaignsCampaignIdLoginRoute
  '/users/$userId/characters': typeof UsersUserIdCharactersRoute
  '/campaigns/$campaignId/': typeof CampaignsCampaignIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/users'
    | '/login'
    | '/campaigns/$campaignId'
    | '/campaigns/new'
    | '/campaigns/'
    | '/users/'
    | '/campaigns/$campaignId/login'
    | '/users/$userId/characters'
    | '/campaigns/$campaignId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/campaigns/new'
    | '/campaigns'
    | '/users'
    | '/campaigns/$campaignId/login'
    | '/users/$userId/characters'
    | '/campaigns/$campaignId'
  id:
    | '__root__'
    | '/'
    | '/users'
    | '/login'
    | '/campaigns/$campaignId'
    | '/campaigns/new'
    | '/campaigns/'
    | '/users/'
    | '/campaigns/$campaignId/login'
    | '/users/$userId/characters'
    | '/campaigns/$campaignId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UsersRouteRoute: typeof UsersRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  CampaignsCampaignIdRouteRoute: typeof CampaignsCampaignIdRouteRouteWithChildren
  CampaignsNewRoute: typeof CampaignsNewRoute
  CampaignsIndexRoute: typeof CampaignsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/': {
      id: '/users/'
      path: '/'
      fullPath: '/users/'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof UsersRouteRoute
    }
    '/campaigns/': {
      id: '/campaigns/'
      path: '/campaigns'
      fullPath: '/campaigns/'
      preLoaderRoute: typeof CampaignsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/new': {
      id: '/campaigns/new'
      path: '/campaigns/new'
      fullPath: '/campaigns/new'
      preLoaderRoute: typeof CampaignsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$campaignId': {
      id: '/campaigns/$campaignId'
      path: '/campaigns/$campaignId'
      fullPath: '/campaigns/$campaignId'
      preLoaderRoute: typeof CampaignsCampaignIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$campaignId/': {
      id: '/campaigns/$campaignId/'
      path: '/'
      fullPath: '/campaigns/$campaignId/'
      preLoaderRoute: typeof CampaignsCampaignIdIndexRouteImport
      parentRoute: typeof CampaignsCampaignIdRouteRoute
    }
    '/users/$userId/characters': {
      id: '/users/$userId/characters'
      path: '/$userId/characters'
      fullPath: '/users/$userId/characters'
      preLoaderRoute: typeof UsersUserIdCharactersRouteImport
      parentRoute: typeof UsersRouteRoute
    }
    '/campaigns/$campaignId/login': {
      id: '/campaigns/$campaignId/login'
      path: '/login'
      fullPath: '/campaigns/$campaignId/login'
      preLoaderRoute: typeof CampaignsCampaignIdLoginRouteImport
      parentRoute: typeof CampaignsCampaignIdRouteRoute
    }
  }
}

interface UsersRouteRouteChildren {
  UsersIndexRoute: typeof UsersIndexRoute
  UsersUserIdCharactersRoute: typeof UsersUserIdCharactersRoute
}

const UsersRouteRouteChildren: UsersRouteRouteChildren = {
  UsersIndexRoute: UsersIndexRoute,
  UsersUserIdCharactersRoute: UsersUserIdCharactersRoute,
}

const UsersRouteRouteWithChildren = UsersRouteRoute._addFileChildren(
  UsersRouteRouteChildren,
)

interface CampaignsCampaignIdRouteRouteChildren {
  CampaignsCampaignIdLoginRoute: typeof CampaignsCampaignIdLoginRoute
  CampaignsCampaignIdIndexRoute: typeof CampaignsCampaignIdIndexRoute
}

const CampaignsCampaignIdRouteRouteChildren: CampaignsCampaignIdRouteRouteChildren =
  {
    CampaignsCampaignIdLoginRoute: CampaignsCampaignIdLoginRoute,
    CampaignsCampaignIdIndexRoute: CampaignsCampaignIdIndexRoute,
  }

const CampaignsCampaignIdRouteRouteWithChildren =
  CampaignsCampaignIdRouteRoute._addFileChildren(
    CampaignsCampaignIdRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UsersRouteRoute: UsersRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  CampaignsCampaignIdRouteRoute: CampaignsCampaignIdRouteRouteWithChildren,
  CampaignsNewRoute: CampaignsNewRoute,
  CampaignsIndexRoute: CampaignsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
