/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as UsersRouteRouteImport } from './routes/users/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersIndexRouteImport } from './routes/users/index'
import { Route as CampaignsIndexRouteImport } from './routes/campaigns/index'
import { Route as UsersMeRouteImport } from './routes/users/me'
import { Route as CampaignsNewRouteImport } from './routes/campaigns/new'
import { Route as CampaignsCampaignIdRouteRouteImport } from './routes/campaigns/$campaignId/route'
import { Route as CampaignsCampaignIdIndexRouteImport } from './routes/campaigns/$campaignId/index'
import { Route as UsersUserIdCharactersRouteImport } from './routes/users/$userId.characters'
import { Route as CampaignsCampaignIdLoginRouteImport } from './routes/campaigns/$campaignId/login'
import { Route as CampaignsCampaignIdChatRouteImport } from './routes/campaigns/$campaignId/chat'
import { Route as CampaignsCampaignIdCharacterRouteImport } from './routes/campaigns/$campaignId/character'
import { Route as CampaignsCampaignIdPlayersRouteRouteImport } from './routes/campaigns/$campaignId/players/route'
import { Route as CampaignsCampaignIdPlayRouteRouteImport } from './routes/campaigns/$campaignId/play/route'
import { Route as CampaignsCampaignIdJournalRouteRouteImport } from './routes/campaigns/$campaignId/journal/route'
import { Route as CampaignsCampaignIdAdminRouteRouteImport } from './routes/campaigns/$campaignId/admin/route'
import { Route as CampaignsCampaignIdAdminIndexRouteImport } from './routes/campaigns/$campaignId/admin/index'
import { Route as CampaignsCampaignIdPlayersAddRouteImport } from './routes/campaigns/$campaignId/players/add'
import { Route as CampaignsCampaignIdAdminTreesRouteImport } from './routes/campaigns/$campaignId/admin/trees'
import { Route as CampaignsCampaignIdAdminTreesTreeIdRouteImport } from './routes/campaigns/$campaignId/admin/trees_.$treeId'
import { Route as CampaignsCampaignIdAdminNodesNodeIdRouteImport } from './routes/campaigns/$campaignId/admin/nodes_.$nodeId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRouteRoute = UsersRouteRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UsersRouteRoute,
} as any)
const CampaignsIndexRoute = CampaignsIndexRouteImport.update({
  id: '/campaigns/',
  path: '/campaigns/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersMeRoute = UsersMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => UsersRouteRoute,
} as any)
const CampaignsNewRoute = CampaignsNewRouteImport.update({
  id: '/campaigns/new',
  path: '/campaigns/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsCampaignIdRouteRoute =
  CampaignsCampaignIdRouteRouteImport.update({
    id: '/campaigns/$campaignId',
    path: '/campaigns/$campaignId',
    getParentRoute: () => rootRouteImport,
  } as any)
const CampaignsCampaignIdIndexRoute =
  CampaignsCampaignIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => CampaignsCampaignIdRouteRoute,
  } as any)
const UsersUserIdCharactersRoute = UsersUserIdCharactersRouteImport.update({
  id: '/$userId/characters',
  path: '/$userId/characters',
  getParentRoute: () => UsersRouteRoute,
} as any)
const CampaignsCampaignIdLoginRoute =
  CampaignsCampaignIdLoginRouteImport.update({
    id: '/login',
    path: '/login',
    getParentRoute: () => CampaignsCampaignIdRouteRoute,
  } as any)
const CampaignsCampaignIdChatRoute = CampaignsCampaignIdChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => CampaignsCampaignIdRouteRoute,
} as any)
const CampaignsCampaignIdCharacterRoute =
  CampaignsCampaignIdCharacterRouteImport.update({
    id: '/character',
    path: '/character',
    getParentRoute: () => CampaignsCampaignIdRouteRoute,
  } as any)
const CampaignsCampaignIdPlayersRouteRoute =
  CampaignsCampaignIdPlayersRouteRouteImport.update({
    id: '/players',
    path: '/players',
    getParentRoute: () => CampaignsCampaignIdRouteRoute,
  } as any)
const CampaignsCampaignIdPlayRouteRoute =
  CampaignsCampaignIdPlayRouteRouteImport.update({
    id: '/play',
    path: '/play',
    getParentRoute: () => CampaignsCampaignIdRouteRoute,
  } as any)
const CampaignsCampaignIdJournalRouteRoute =
  CampaignsCampaignIdJournalRouteRouteImport.update({
    id: '/journal',
    path: '/journal',
    getParentRoute: () => CampaignsCampaignIdRouteRoute,
  } as any)
const CampaignsCampaignIdAdminRouteRoute =
  CampaignsCampaignIdAdminRouteRouteImport.update({
    id: '/admin',
    path: '/admin',
    getParentRoute: () => CampaignsCampaignIdRouteRoute,
  } as any)
const CampaignsCampaignIdAdminIndexRoute =
  CampaignsCampaignIdAdminIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => CampaignsCampaignIdAdminRouteRoute,
  } as any)
const CampaignsCampaignIdPlayersAddRoute =
  CampaignsCampaignIdPlayersAddRouteImport.update({
    id: '/add',
    path: '/add',
    getParentRoute: () => CampaignsCampaignIdPlayersRouteRoute,
  } as any)
const CampaignsCampaignIdAdminTreesRoute =
  CampaignsCampaignIdAdminTreesRouteImport.update({
    id: '/trees',
    path: '/trees',
    getParentRoute: () => CampaignsCampaignIdAdminRouteRoute,
  } as any)
const CampaignsCampaignIdAdminTreesTreeIdRoute =
  CampaignsCampaignIdAdminTreesTreeIdRouteImport.update({
    id: '/trees_/$treeId',
    path: '/trees/$treeId',
    getParentRoute: () => CampaignsCampaignIdAdminRouteRoute,
  } as any)
const CampaignsCampaignIdAdminNodesNodeIdRoute =
  CampaignsCampaignIdAdminNodesNodeIdRouteImport.update({
    id: '/nodes_/$nodeId',
    path: '/nodes/$nodeId',
    getParentRoute: () => CampaignsCampaignIdAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/users': typeof UsersRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/campaigns/$campaignId': typeof CampaignsCampaignIdRouteRouteWithChildren
  '/campaigns/new': typeof CampaignsNewRoute
  '/users/me': typeof UsersMeRoute
  '/campaigns/': typeof CampaignsIndexRoute
  '/users/': typeof UsersIndexRoute
  '/campaigns/$campaignId/admin': typeof CampaignsCampaignIdAdminRouteRouteWithChildren
  '/campaigns/$campaignId/journal': typeof CampaignsCampaignIdJournalRouteRoute
  '/campaigns/$campaignId/play': typeof CampaignsCampaignIdPlayRouteRoute
  '/campaigns/$campaignId/players': typeof CampaignsCampaignIdPlayersRouteRouteWithChildren
  '/campaigns/$campaignId/character': typeof CampaignsCampaignIdCharacterRoute
  '/campaigns/$campaignId/chat': typeof CampaignsCampaignIdChatRoute
  '/campaigns/$campaignId/login': typeof CampaignsCampaignIdLoginRoute
  '/users/$userId/characters': typeof UsersUserIdCharactersRoute
  '/campaigns/$campaignId/': typeof CampaignsCampaignIdIndexRoute
  '/campaigns/$campaignId/admin/trees': typeof CampaignsCampaignIdAdminTreesRoute
  '/campaigns/$campaignId/players/add': typeof CampaignsCampaignIdPlayersAddRoute
  '/campaigns/$campaignId/admin/': typeof CampaignsCampaignIdAdminIndexRoute
  '/campaigns/$campaignId/admin/nodes/$nodeId': typeof CampaignsCampaignIdAdminNodesNodeIdRoute
  '/campaigns/$campaignId/admin/trees/$treeId': typeof CampaignsCampaignIdAdminTreesTreeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/campaigns/new': typeof CampaignsNewRoute
  '/users/me': typeof UsersMeRoute
  '/campaigns': typeof CampaignsIndexRoute
  '/users': typeof UsersIndexRoute
  '/campaigns/$campaignId/journal': typeof CampaignsCampaignIdJournalRouteRoute
  '/campaigns/$campaignId/play': typeof CampaignsCampaignIdPlayRouteRoute
  '/campaigns/$campaignId/players': typeof CampaignsCampaignIdPlayersRouteRouteWithChildren
  '/campaigns/$campaignId/character': typeof CampaignsCampaignIdCharacterRoute
  '/campaigns/$campaignId/chat': typeof CampaignsCampaignIdChatRoute
  '/campaigns/$campaignId/login': typeof CampaignsCampaignIdLoginRoute
  '/users/$userId/characters': typeof UsersUserIdCharactersRoute
  '/campaigns/$campaignId': typeof CampaignsCampaignIdIndexRoute
  '/campaigns/$campaignId/admin/trees': typeof CampaignsCampaignIdAdminTreesRoute
  '/campaigns/$campaignId/players/add': typeof CampaignsCampaignIdPlayersAddRoute
  '/campaigns/$campaignId/admin': typeof CampaignsCampaignIdAdminIndexRoute
  '/campaigns/$campaignId/admin/nodes/$nodeId': typeof CampaignsCampaignIdAdminNodesNodeIdRoute
  '/campaigns/$campaignId/admin/trees/$treeId': typeof CampaignsCampaignIdAdminTreesTreeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/users': typeof UsersRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/campaigns/$campaignId': typeof CampaignsCampaignIdRouteRouteWithChildren
  '/campaigns/new': typeof CampaignsNewRoute
  '/users/me': typeof UsersMeRoute
  '/campaigns/': typeof CampaignsIndexRoute
  '/users/': typeof UsersIndexRoute
  '/campaigns/$campaignId/admin': typeof CampaignsCampaignIdAdminRouteRouteWithChildren
  '/campaigns/$campaignId/journal': typeof CampaignsCampaignIdJournalRouteRoute
  '/campaigns/$campaignId/play': typeof CampaignsCampaignIdPlayRouteRoute
  '/campaigns/$campaignId/players': typeof CampaignsCampaignIdPlayersRouteRouteWithChildren
  '/campaigns/$campaignId/character': typeof CampaignsCampaignIdCharacterRoute
  '/campaigns/$campaignId/chat': typeof CampaignsCampaignIdChatRoute
  '/campaigns/$campaignId/login': typeof CampaignsCampaignIdLoginRoute
  '/users/$userId/characters': typeof UsersUserIdCharactersRoute
  '/campaigns/$campaignId/': typeof CampaignsCampaignIdIndexRoute
  '/campaigns/$campaignId/admin/trees': typeof CampaignsCampaignIdAdminTreesRoute
  '/campaigns/$campaignId/players/add': typeof CampaignsCampaignIdPlayersAddRoute
  '/campaigns/$campaignId/admin/': typeof CampaignsCampaignIdAdminIndexRoute
  '/campaigns/$campaignId/admin/nodes_/$nodeId': typeof CampaignsCampaignIdAdminNodesNodeIdRoute
  '/campaigns/$campaignId/admin/trees_/$treeId': typeof CampaignsCampaignIdAdminTreesTreeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/users'
    | '/login'
    | '/campaigns/$campaignId'
    | '/campaigns/new'
    | '/users/me'
    | '/campaigns/'
    | '/users/'
    | '/campaigns/$campaignId/admin'
    | '/campaigns/$campaignId/journal'
    | '/campaigns/$campaignId/play'
    | '/campaigns/$campaignId/players'
    | '/campaigns/$campaignId/character'
    | '/campaigns/$campaignId/chat'
    | '/campaigns/$campaignId/login'
    | '/users/$userId/characters'
    | '/campaigns/$campaignId/'
    | '/campaigns/$campaignId/admin/trees'
    | '/campaigns/$campaignId/players/add'
    | '/campaigns/$campaignId/admin/'
    | '/campaigns/$campaignId/admin/nodes/$nodeId'
    | '/campaigns/$campaignId/admin/trees/$treeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/campaigns/new'
    | '/users/me'
    | '/campaigns'
    | '/users'
    | '/campaigns/$campaignId/journal'
    | '/campaigns/$campaignId/play'
    | '/campaigns/$campaignId/players'
    | '/campaigns/$campaignId/character'
    | '/campaigns/$campaignId/chat'
    | '/campaigns/$campaignId/login'
    | '/users/$userId/characters'
    | '/campaigns/$campaignId'
    | '/campaigns/$campaignId/admin/trees'
    | '/campaigns/$campaignId/players/add'
    | '/campaigns/$campaignId/admin'
    | '/campaigns/$campaignId/admin/nodes/$nodeId'
    | '/campaigns/$campaignId/admin/trees/$treeId'
  id:
    | '__root__'
    | '/'
    | '/users'
    | '/login'
    | '/campaigns/$campaignId'
    | '/campaigns/new'
    | '/users/me'
    | '/campaigns/'
    | '/users/'
    | '/campaigns/$campaignId/admin'
    | '/campaigns/$campaignId/journal'
    | '/campaigns/$campaignId/play'
    | '/campaigns/$campaignId/players'
    | '/campaigns/$campaignId/character'
    | '/campaigns/$campaignId/chat'
    | '/campaigns/$campaignId/login'
    | '/users/$userId/characters'
    | '/campaigns/$campaignId/'
    | '/campaigns/$campaignId/admin/trees'
    | '/campaigns/$campaignId/players/add'
    | '/campaigns/$campaignId/admin/'
    | '/campaigns/$campaignId/admin/nodes_/$nodeId'
    | '/campaigns/$campaignId/admin/trees_/$treeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UsersRouteRoute: typeof UsersRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  CampaignsCampaignIdRouteRoute: typeof CampaignsCampaignIdRouteRouteWithChildren
  CampaignsNewRoute: typeof CampaignsNewRoute
  CampaignsIndexRoute: typeof CampaignsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/': {
      id: '/users/'
      path: '/'
      fullPath: '/users/'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof UsersRouteRoute
    }
    '/campaigns/': {
      id: '/campaigns/'
      path: '/campaigns'
      fullPath: '/campaigns/'
      preLoaderRoute: typeof CampaignsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/me': {
      id: '/users/me'
      path: '/me'
      fullPath: '/users/me'
      preLoaderRoute: typeof UsersMeRouteImport
      parentRoute: typeof UsersRouteRoute
    }
    '/campaigns/new': {
      id: '/campaigns/new'
      path: '/campaigns/new'
      fullPath: '/campaigns/new'
      preLoaderRoute: typeof CampaignsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$campaignId': {
      id: '/campaigns/$campaignId'
      path: '/campaigns/$campaignId'
      fullPath: '/campaigns/$campaignId'
      preLoaderRoute: typeof CampaignsCampaignIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$campaignId/': {
      id: '/campaigns/$campaignId/'
      path: '/'
      fullPath: '/campaigns/$campaignId/'
      preLoaderRoute: typeof CampaignsCampaignIdIndexRouteImport
      parentRoute: typeof CampaignsCampaignIdRouteRoute
    }
    '/users/$userId/characters': {
      id: '/users/$userId/characters'
      path: '/$userId/characters'
      fullPath: '/users/$userId/characters'
      preLoaderRoute: typeof UsersUserIdCharactersRouteImport
      parentRoute: typeof UsersRouteRoute
    }
    '/campaigns/$campaignId/login': {
      id: '/campaigns/$campaignId/login'
      path: '/login'
      fullPath: '/campaigns/$campaignId/login'
      preLoaderRoute: typeof CampaignsCampaignIdLoginRouteImport
      parentRoute: typeof CampaignsCampaignIdRouteRoute
    }
    '/campaigns/$campaignId/chat': {
      id: '/campaigns/$campaignId/chat'
      path: '/chat'
      fullPath: '/campaigns/$campaignId/chat'
      preLoaderRoute: typeof CampaignsCampaignIdChatRouteImport
      parentRoute: typeof CampaignsCampaignIdRouteRoute
    }
    '/campaigns/$campaignId/character': {
      id: '/campaigns/$campaignId/character'
      path: '/character'
      fullPath: '/campaigns/$campaignId/character'
      preLoaderRoute: typeof CampaignsCampaignIdCharacterRouteImport
      parentRoute: typeof CampaignsCampaignIdRouteRoute
    }
    '/campaigns/$campaignId/players': {
      id: '/campaigns/$campaignId/players'
      path: '/players'
      fullPath: '/campaigns/$campaignId/players'
      preLoaderRoute: typeof CampaignsCampaignIdPlayersRouteRouteImport
      parentRoute: typeof CampaignsCampaignIdRouteRoute
    }
    '/campaigns/$campaignId/play': {
      id: '/campaigns/$campaignId/play'
      path: '/play'
      fullPath: '/campaigns/$campaignId/play'
      preLoaderRoute: typeof CampaignsCampaignIdPlayRouteRouteImport
      parentRoute: typeof CampaignsCampaignIdRouteRoute
    }
    '/campaigns/$campaignId/journal': {
      id: '/campaigns/$campaignId/journal'
      path: '/journal'
      fullPath: '/campaigns/$campaignId/journal'
      preLoaderRoute: typeof CampaignsCampaignIdJournalRouteRouteImport
      parentRoute: typeof CampaignsCampaignIdRouteRoute
    }
    '/campaigns/$campaignId/admin': {
      id: '/campaigns/$campaignId/admin'
      path: '/admin'
      fullPath: '/campaigns/$campaignId/admin'
      preLoaderRoute: typeof CampaignsCampaignIdAdminRouteRouteImport
      parentRoute: typeof CampaignsCampaignIdRouteRoute
    }
    '/campaigns/$campaignId/admin/': {
      id: '/campaigns/$campaignId/admin/'
      path: '/'
      fullPath: '/campaigns/$campaignId/admin/'
      preLoaderRoute: typeof CampaignsCampaignIdAdminIndexRouteImport
      parentRoute: typeof CampaignsCampaignIdAdminRouteRoute
    }
    '/campaigns/$campaignId/players/add': {
      id: '/campaigns/$campaignId/players/add'
      path: '/add'
      fullPath: '/campaigns/$campaignId/players/add'
      preLoaderRoute: typeof CampaignsCampaignIdPlayersAddRouteImport
      parentRoute: typeof CampaignsCampaignIdPlayersRouteRoute
    }
    '/campaigns/$campaignId/admin/trees': {
      id: '/campaigns/$campaignId/admin/trees'
      path: '/trees'
      fullPath: '/campaigns/$campaignId/admin/trees'
      preLoaderRoute: typeof CampaignsCampaignIdAdminTreesRouteImport
      parentRoute: typeof CampaignsCampaignIdAdminRouteRoute
    }
    '/campaigns/$campaignId/admin/trees_/$treeId': {
      id: '/campaigns/$campaignId/admin/trees_/$treeId'
      path: '/trees/$treeId'
      fullPath: '/campaigns/$campaignId/admin/trees/$treeId'
      preLoaderRoute: typeof CampaignsCampaignIdAdminTreesTreeIdRouteImport
      parentRoute: typeof CampaignsCampaignIdAdminRouteRoute
    }
    '/campaigns/$campaignId/admin/nodes_/$nodeId': {
      id: '/campaigns/$campaignId/admin/nodes_/$nodeId'
      path: '/nodes/$nodeId'
      fullPath: '/campaigns/$campaignId/admin/nodes/$nodeId'
      preLoaderRoute: typeof CampaignsCampaignIdAdminNodesNodeIdRouteImport
      parentRoute: typeof CampaignsCampaignIdAdminRouteRoute
    }
  }
}

interface UsersRouteRouteChildren {
  UsersMeRoute: typeof UsersMeRoute
  UsersIndexRoute: typeof UsersIndexRoute
  UsersUserIdCharactersRoute: typeof UsersUserIdCharactersRoute
}

const UsersRouteRouteChildren: UsersRouteRouteChildren = {
  UsersMeRoute: UsersMeRoute,
  UsersIndexRoute: UsersIndexRoute,
  UsersUserIdCharactersRoute: UsersUserIdCharactersRoute,
}

const UsersRouteRouteWithChildren = UsersRouteRoute._addFileChildren(
  UsersRouteRouteChildren,
)

interface CampaignsCampaignIdAdminRouteRouteChildren {
  CampaignsCampaignIdAdminTreesRoute: typeof CampaignsCampaignIdAdminTreesRoute
  CampaignsCampaignIdAdminIndexRoute: typeof CampaignsCampaignIdAdminIndexRoute
  CampaignsCampaignIdAdminNodesNodeIdRoute: typeof CampaignsCampaignIdAdminNodesNodeIdRoute
  CampaignsCampaignIdAdminTreesTreeIdRoute: typeof CampaignsCampaignIdAdminTreesTreeIdRoute
}

const CampaignsCampaignIdAdminRouteRouteChildren: CampaignsCampaignIdAdminRouteRouteChildren =
  {
    CampaignsCampaignIdAdminTreesRoute: CampaignsCampaignIdAdminTreesRoute,
    CampaignsCampaignIdAdminIndexRoute: CampaignsCampaignIdAdminIndexRoute,
    CampaignsCampaignIdAdminNodesNodeIdRoute:
      CampaignsCampaignIdAdminNodesNodeIdRoute,
    CampaignsCampaignIdAdminTreesTreeIdRoute:
      CampaignsCampaignIdAdminTreesTreeIdRoute,
  }

const CampaignsCampaignIdAdminRouteRouteWithChildren =
  CampaignsCampaignIdAdminRouteRoute._addFileChildren(
    CampaignsCampaignIdAdminRouteRouteChildren,
  )

interface CampaignsCampaignIdPlayersRouteRouteChildren {
  CampaignsCampaignIdPlayersAddRoute: typeof CampaignsCampaignIdPlayersAddRoute
}

const CampaignsCampaignIdPlayersRouteRouteChildren: CampaignsCampaignIdPlayersRouteRouteChildren =
  {
    CampaignsCampaignIdPlayersAddRoute: CampaignsCampaignIdPlayersAddRoute,
  }

const CampaignsCampaignIdPlayersRouteRouteWithChildren =
  CampaignsCampaignIdPlayersRouteRoute._addFileChildren(
    CampaignsCampaignIdPlayersRouteRouteChildren,
  )

interface CampaignsCampaignIdRouteRouteChildren {
  CampaignsCampaignIdAdminRouteRoute: typeof CampaignsCampaignIdAdminRouteRouteWithChildren
  CampaignsCampaignIdJournalRouteRoute: typeof CampaignsCampaignIdJournalRouteRoute
  CampaignsCampaignIdPlayRouteRoute: typeof CampaignsCampaignIdPlayRouteRoute
  CampaignsCampaignIdPlayersRouteRoute: typeof CampaignsCampaignIdPlayersRouteRouteWithChildren
  CampaignsCampaignIdCharacterRoute: typeof CampaignsCampaignIdCharacterRoute
  CampaignsCampaignIdChatRoute: typeof CampaignsCampaignIdChatRoute
  CampaignsCampaignIdLoginRoute: typeof CampaignsCampaignIdLoginRoute
  CampaignsCampaignIdIndexRoute: typeof CampaignsCampaignIdIndexRoute
}

const CampaignsCampaignIdRouteRouteChildren: CampaignsCampaignIdRouteRouteChildren =
  {
    CampaignsCampaignIdAdminRouteRoute:
      CampaignsCampaignIdAdminRouteRouteWithChildren,
    CampaignsCampaignIdJournalRouteRoute: CampaignsCampaignIdJournalRouteRoute,
    CampaignsCampaignIdPlayRouteRoute: CampaignsCampaignIdPlayRouteRoute,
    CampaignsCampaignIdPlayersRouteRoute:
      CampaignsCampaignIdPlayersRouteRouteWithChildren,
    CampaignsCampaignIdCharacterRoute: CampaignsCampaignIdCharacterRoute,
    CampaignsCampaignIdChatRoute: CampaignsCampaignIdChatRoute,
    CampaignsCampaignIdLoginRoute: CampaignsCampaignIdLoginRoute,
    CampaignsCampaignIdIndexRoute: CampaignsCampaignIdIndexRoute,
  }

const CampaignsCampaignIdRouteRouteWithChildren =
  CampaignsCampaignIdRouteRoute._addFileChildren(
    CampaignsCampaignIdRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UsersRouteRoute: UsersRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  CampaignsCampaignIdRouteRoute: CampaignsCampaignIdRouteRouteWithChildren,
  CampaignsNewRoute: CampaignsNewRoute,
  CampaignsIndexRoute: CampaignsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
